id: A71D9A2FC
title: In Praise of the Eight Siddhas
type: translation
pechas:
- I888BBD9F
- I9C333FF3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:58.603143
  last_modified_at: 2023-01-04 11:44:58.603155
  collections:
  - Dolpopa Sherab Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I888BBD9F/99AA: 156A
  I9C333FF3/3C2D: 156A
